version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
    steps:
      - checkout

      - run:
          name: Install test dependencies
          command: |
            sudo curl -o /usr/local/bin/circleci https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci && sudo chmod +x /usr/local/bin/circleci
            sudo ./install-composer.sh

      - run:
          name: Run tests
          command: ./test.sh $CIRCLE_BRANCH

      - run:
          name: Move artifacts
          command: |
            mkdir artifacts
            mv test_this_branch test_last_tag artifacts

      - store_artifacts:
          path: artifacts
