version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Run tests
          command: ./test.sh $CIRCLE_BRANCH

      - run:
          name: Move artifacts
          command: |
            mkdir artifacts
            mv test_this_branch test_last_tag fb_instant_articles artifacts

      - store_artifacts:
          path: artifacts
